- repo: git://github.com/pre-commit/mirrors-scss-lint
  sha: v0.50.2  # Use the sha you want to point at
  hooks:
  - id: scss-lint
    args: [--config=src/scss/.scss-lint.yml, --exclude=src/scss/libraries/, --color]
    stages: [push]
